package osman_kartal_ooad_hw1_p2;

import java.util.Observable;
import java.util.Observer;

/**
 * CurrentPhotoDisplay is a concrete class that implements Observer and
 * DisplayElement interfaces. It is one of the observer type.
 *
 * Whenever a new content is generated by Website class the update method
 * in this class is called so that new content can be changed with older one
 * and shown to the user.
 *
 * CurrentPhotoDisplay is the observer type that interests in photos
 * that Website serves.
 *
 * @author Osman Kartal
 */
public class CurrentPhotoDisplay implements Observer, DisplayElement{
    /**
     * Used for communicate with Website Class so that new content
     * can be extracted.
     */
    private Observable observable;

    /**
     * String that simulates a photograph data in a text format like
     * "image.jpeg"
     */
    private String photo;

    /**
     * One parameter constructor
     * @param observable Observable that register this observer
     */
    CurrentPhotoDisplay(Observable observable) {
        this.observable = observable;
        observable.addObserver(this);
    }

    /**
     * Updates the old content and display new ones.
     *
     * @param obs Website
     * @param arg
     */
    public void update(Observable obs, Object arg) {
        if (obs instanceof Website) {
            Website website = (Website) obs;
            this.photo = website.getPhoto();
            display();
        }
    }

    /**
     * Displays photo that currently arrived from subscribed Website.
     */
    public void display() {
        System.out.println("CurrentPhotoDisplay -> New photo: " + photo);
    }
}
