package osman_kartal_ooad_hw1_p2;

import java.util.Observable;
import java.util.Observer;

/**
 * CurrentAllDisplay is a concrete class that implements Observer and
 * DisplayElement interfaces. It is one of the observer type.
 *
 * Whenever a new content is generated by Website class the update method
 * in this class is called so that new content can be changed with older one
 * and shown to the user.
 *
 * CurrentAllDisplay is the observer type that interests in all kind of media
 * that Website contains(photo, text, audio).
 *
 * @author Osman Kartal
 */
public class CurrentAllDisplay implements Observer, DisplayElement{
    /**
     * Used for communicate with Website Class so that new content
     * can be extracted.
     */
    Observable observable;

    /**
     * String that simulates a photograph data in a text format like
     * "image.jpeg"
     */
    private String photo;

    /**
     * String that simulates a text data.
     */
    private String text;

    /**
     * String that simulates a audio data in a text format like
     * "audio.mp3"
     */
    private String audio;

    /**
     * One parameter constructor
     * @param observable Observable that register this observer
     */
    CurrentAllDisplay(Observable observable) {
        // Get the reference of the website.
        this.observable = observable;
        // Subscribe to the website.
        observable.addObserver(this);
    }

    /**
     * Updates the old content and display new ones.
     *
     * @param obs Website
     * @param arg
     */
    public void update(Observable obs, Object arg) {
        // Observable is more generic. It can be a class different than Website
        // Check whether it is a Website object.
        if (obs instanceof Website) {
            Website website = (Website) obs;
            this.photo = website.getPhoto();
            this.text = website.getText();
            this.audio = website.getAudio();
            display();
        }
    }

    /**
     * Displays elements that currently arrived from subscribed Website.
     */
    public void display() {
        System.out.println("CurrentAllDisplay -> New photo: " + photo +
                " | New text: " + text + " | New audio: " + audio);
    }
}
